# Inkline - Development Funding
# Thank you, everyone! Inkline is only thriving because of its amazing community. 

github: [inkline]
patreon: inkline
open_collective: # Replace with a single Open Collective username
ko_fi: inkline
